/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.winecompliance;
import static org.hamcrest.Matchers.equalTo;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;

@SpringBootTest
@AutoConfigureMockMvc
public class AppTest {
    @Autowired
    private MockMvc mvc;

    @Test
    public void getInvalidLotCode() throws Exception {
        mvc.perform(MockMvcRequestBuilders.get("/api/breakdown/wine/ABC").accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(content().string(equalTo("null")));
    }

    @Test
    public void getValidLotCode() throws Exception {
        mvc.perform(MockMvcRequestBuilders.get("/api/breakdown/wine/11YVCHAR001").accept(MediaType.APPLICATION_JSON))
                .andExpect(status().isOk())
                .andExpect(content().string(equalTo("{\"lotCode\":\"11YVCHAR001\",\"volume\":1000.0,\"description\":\"2011 Yarra Valley Chardonnay\",\"tankCode\":\"T25-01\",\"productState\":\"Ready for bottling\",\"ownerName\":\"YV Wines Pty Ltd\",\"components\":[{\"percentage\":5.0,\"year\":2011,\"variety\":\"Pinot Noir\",\"region\":\"Mornington\"},{\"percentage\":80.0,\"year\":2011,\"variety\":\"Chardonnay\",\"region\":\"Yarra Valley\"},{\"percentage\":5.0,\"year\":2010,\"variety\":\"Pinot Noir\",\"region\":\"Macedon\"},{\"percentage\":10.0,\"year\":2010,\"variety\":\"Chardonnay\",\"region\":\"Macedon\"}]}")));
    }
}